baseURL = 'https://dominguezsamuel.com/'
languageCode = 'en-us'
title = 'Purple Perch'
theme = 'paper'
author = "SD"
ignoreErrors = ["error-remote-getjson"]

[params]
  color = 'wheat'

  # twitter = 'nanxiaobei'
  # github = 'nanxiaobei'
  # instagram = 'nan.xiaobei'

  # avatar = 'nanxiaobei@gmail.com'
  name = 'Purple Perch'
  bio = 'Where the falcon dwells at dusk.'
# ------------------------------

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
#  [markup.highlight]
#    lineNos = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 2 

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

