name: Copy folder to other branch

on: [push]

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Build the site in the jekyll/builder container
        env:
          BUILD_BRANCH: master
          TARGET_BRANCH: static
          SRC_FOLDER_PATH: _site
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -A
          git commit -m "jekyll build files"
          git push
          files=$(find $SRC_FOLDER_PATH -type f) # get the file list
          git fetch                         # fetch branches
          git checkout $TARGET_BRANCH       # checkout to your branch
          git rm -rf * --ignore-unmatch
          git checkout ${GITHUB_REF##*/} -- $files # copy files from the source branch
          mv $SRC_FOLDER_PATH/* .
          rmdir $SRC_FOLDER_PATH
          git add -A
          git diff-index --quiet HEAD ||  git commit -am "deploy files"  # commit to the repository (ignore if no modification)
          git push origin $TARGET_BRANCH # push to remote branch
          
